target-version = "py312"

line-length = 125

[lint]
select = ["ALL"]
ignore = [
  "ANN003", # missing-type-kwargs
  "D100",   # undocumented-public-module
  "S607"    # start-process-with-partial-path
]
