name: CI

on:
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: 3.12
          cache-local-path: /tmp/uv_cache_dir # Workaround for https://github.com/hynek/build-and-inspect-python-package/issues/181

      - uses: astral-sh/ruff-action@v4.0.0
      - run: ruff check
      - run: ruff format --check
