name: CI

on:
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: 3.12
          enable-cache: "false"

      - uses: astral-sh/ruff-action@v4.0.0
      - run: ruff check
